[accounts.kybe]
default = true
email = "kybe@kybe.xyz"
display-name = "kybe"
downloads-dir = "/home/kybe/Downloads"
backend.type = "imap"
backend.host = "mail.kybe.xyz"
backend.port = 993
backend.login = "kybe@kybe.xyz"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "cat /run/secrets/kybe-imap"
message.send.backend.type = "smtp"
message.send.backend.host = "mail.kybe.xyz"
message.send.backend.port = 465
message.send.backend.login = "kybe@kybe.xyz"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "cat /run/secrets/kybe-imap"
